# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2026 The War Powers authors
#
# Writes wp_build_id.h with the current git description (short hash, plus
# "-dirty" when the tree has uncommitted changes). Runs on every build via the
# wp_build_id target; the header is only rewritten when the id changes.
set(WP_BUILD_ID "unknown")
find_package(Git QUIET)
if(GIT_FOUND)
    execute_process(
        COMMAND ${GIT_EXECUTABLE} describe --always --dirty --exclude "*"
        WORKING_DIRECTORY ${WP_SOURCE_DIR}
        OUTPUT_VARIABLE WP_GIT_DESCRIBE
        OUTPUT_STRIP_TRAILING_WHITESPACE
        RESULT_VARIABLE WP_GIT_RESULT
        ERROR_QUIET
    )
    if(WP_GIT_RESULT EQUAL 0 AND WP_GIT_DESCRIBE)
        set(WP_BUILD_ID "${WP_GIT_DESCRIBE}")
    endif()
endif()
set(WP_CONTENT "// Generated by wp_build_id.cmake; do not edit.\n#pragma once\n#define WP_BUILD_ID \"${WP_BUILD_ID}\"\n")
set(WP_EXISTING "")
if(EXISTS "${WP_BUILD_ID_HEADER}")
    file(READ "${WP_BUILD_ID_HEADER}" WP_EXISTING)
endif()
if(NOT WP_EXISTING STREQUAL WP_CONTENT)
    file(WRITE "${WP_BUILD_ID_HEADER}" "${WP_CONTENT}")
endif()
